USE [siga_intellectus]
GO

/****** Object:  View [dbo].[V_PROG_DISCDOC]    Script Date: 28/04/2019 18:42:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[V_PROG_DISCDOC] AS
SELECT  ROW_NUMBER() OVER(ORDER BY B.DISCIPLINA ASC) ID,B.* FROM
(SELECT S.DESCRICAO DISCIPLINA,S.ID DISCIPLINA_ID,C.DESCRICAO CURSO,C.ID CURSO_ID,AL.ANO_LECTIVO,L.CODIGO_DOCENTE DOCENTE,T.TURMA,T.ID CODIGO_TURMA,COUNT(*) TOTAL_AULAS 
	FROM T_LECIONA L,T_DISCIPLINA S,T_ANO_LECTIVO AL,T_CURSO C,T_TURMA T
WHERE L.codigo_disciplina     = S.ID  AND
		  L.CODIGO_ANO_LECTIVO= AL.ID AND
		  L.CODIGO_CURSO      = C.ID  AND
		  L.CODIGO_TURMA=T.ID
GROUP BY S.DESCRICAO,S.ID,L.CODIGO_DOCENTE,AL.ANO_LECTIVO,C.DESCRICAO,C.ID,T.TURMA,T.ID) B

GO


